{% if theme.cnzz_siteid %}

  <div style="display: none;">
    <script type="text/javascript">
    
      var cnzz_protocol = (("https:" == document.location.protocol) ? "https://" : "http://");
      document.write(unescape("%3Cspan id='cnzz_stat_icon_1277697726'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s23.cnzz.com/z_stat.php%3Fid%3D1277697726' type='text/javascript'%3E%3C/script%3E"));
    </script>
  </div>

{% endif %}
